Citylist.create!([
  {code: "L1", name: "Amitabh ", exp: 3, location: " Chennai", rating: 2},
  {code: "L2", name: "Gurmeet ", exp: 4, location: "Bangalore", rating: 4},
  {code: "L3", name: "Arihant ", exp: 10, location: "Indore", rating: 2},
  {code: "L4", name: "Daruka ", exp: 15, location: "Jaipur", rating: 3},
  {code: "L5", name: "Dhanvin ", exp: 3, location: "Bikaner", rating: 2},
  {code: "L6", name: "Eka ", exp: 6, location: " Chennai", rating: 5},
  {code: "L7", name: "Ekapad ", exp: 5, location: " Chennai", rating: 2},
  {code: "L8", name: "Aditya ", exp: 7, location: " Chennai", rating: 5},
  {code: "L9", name: "Anush ", exp: 3, location: "Mohali", rating: 2},
  {code: "L10", name: "Amrit ", exp: 5, location: "Ludhiana", rating: 4},
  {code: "L11", name: "Bimb ", exp: 7, location: "Hyderabad", rating: 2},
  {code: "L12", name: "Balraj ", exp: 10, location: "Jhansi", rating: 4},
  {code: "L13", name: "Bhavin ", exp: 22, location: "Mysore", rating: 2},
  {code: "L14", name: "Anirvan ", exp: 7, location: "Nagpur", rating: 4},
  {code: "L15", name: "Edi ", exp: 9, location: "Pune", rating: 3},
  {code: "L16", name: "Gautam ", exp: 10, location: "Kolkata", rating: 3},
  {code: "L17", name: "Dipesh ", exp: 4, location: "Patna", rating: 4},
  {code: "L18", name: "Falgu ", exp: 3, location: "Lucknow", rating: 5},
  {code: "L19", name: "Ajoy ", exp: 5, location: "Gorakhpur", rating: 3},
  {code: "L20", name: "Giri ", exp: 3, location: "Trichy", rating: 2},
  {code: "L21", name: "Bheru ", exp: 5, location: "Darjeeling", rating: 4},
  {code: "L22", name: "Bankim ", exp: 7, location: "Shimla", rating: 3},
  {code: "L23", name: "Dhiraj ", exp: 10, location: "Surat", rating: 3},
  {code: "L24", name: "Dakshi ", exp: 7, location: "Nasik", rating: 2},
  {code: "L25", name: "Debashish ", exp: 10, location: "Nainital", rating: 4},
  {code: "L26", name: "Devank ", exp: 10, location: "Bhopal", rating: 2},
  {code: "L27", name: "Chitesh ", exp: 15, location: "Bhagalpur", rating: 3},
  {code: "L28", name: "Devadutt ", exp: 5, location: "Secunderabad", rating: 2},
  {code: "L29", name: "Devak ", exp: 7, location: "Vellore", rating: 5},
  {code: "L30", name: "Girindra ", exp: 3, location: "Varanasi", rating: 2},
  {code: "L31", name: "Devpad ", exp: 5, location: "Chennai", rating: 5},
  {code: "L32", name: "Divakar ", exp: 7, location: "Nellore", rating: 2},
  {code: "L33", name: "Gurudas ", exp: 5, location: "Mandya", rating: 4},
  {code: "L34", name: "Gunin ", exp: 7, location: "Mangalore", rating: 2},
  {code: "L35", name: "Chitt ", exp: 5, location: "Ahmedabad", rating: 4},
  {code: "L36", name: "Aakaar ", exp: 7, location: "Noida", rating: 2},
  {code: "L37", name: "Avasyu ", exp: 3, location: "Ghaziabad", rating: 4},
  {code: "L38", name: "Banke ", exp: 5, location: "Joka", rating: 3},
  {code: "L39", name: "Ameya ", exp: 3, location: "Amritsar", rating: 3},
  {code: "L40", name: "Banbihari ", exp: 5, location: "Chandigarh", rating: 4},
  {code: "L41", name: "Chanakya ", exp: 7, location: "Indore", rating: 5},
  {code: "L42", name: "Dakshesh ", exp: 10, location: "Jaipur", rating: 3},
  {code: "L43", name: "Girik ", exp: 3, location: "Bikaner", rating: 2},
  {code: "L44", name: "Ayush ", exp: 5, location: " Chennai", rating: 2},
  {code: "L45", name: "Darpak ", exp: 7, location: " Chennai", rating: 3},
  {code: "L46", name: "Avirat ", exp: 7, location: " Chennai", rating: 5},
  {code: "L47", name: "Gurdayal ", exp: 9, location: "Mohali", rating: 2},
  {code: "L48", name: "Darsh ", exp: 10, location: "Ludhiana", rating: 4},
  {code: "L49", name: "Divyesh ", exp: 4, location: "Hyderabad", rating: 2},
  {code: "L50", name: "Fanibhushan ", exp: 3, location: "Jhansi", rating: 4},
  {code: "L51", name: "Ashish ", exp: 5, location: "Mysore", rating: 2},
  {code: "L52", name: "Atulya ", exp: 3, location: "Nagpur", rating: 4},
  {code: "L53", name: "Dev ", exp: 5, location: "Pune", rating: 2},
  {code: "L54", name: "Abhilash ", exp: 7, location: "Kolkata", rating: 4},
  {code: "L55", name: "Chaitanya ", exp: 10, location: "Patna", rating: 2},
  {code: "L56", name: "Akshar ", exp: 7, location: "Nainital", rating: 4},
  {code: "L57", name: "Abimanyu ", exp: 2, location: "Bhopal", rating: 2},
  {code: "L58", name: "Darpad ", exp: 4, location: "Bhagalpur", rating: 3},
  {code: "L59", name: "Ajay ", exp: 8, location: "Secunderabad", rating: 2},
  {code: "L60", name: "Adinath ", exp: 6, location: "Vellore", rating: 5},
  {code: "L61", name: "Apu ", exp: 12, location: "Varanasi", rating: 2},
  {code: "L62", name: "Angada ", exp: 4, location: "Chennai", rating: 5},
  {code: "L63", name: "Angaj ", exp: 8, location: "Noida", rating: 2},
  {code: "L64", name: "Anshul ", exp: 14, location: "Ghaziabad", rating: 4},
  {code: "L65", name: "Gaurav ", exp: 2, location: "Joka", rating: 2},
  {code: "L66", name: "Gurudatt ", exp: 1, location: "Amritsar", rating: 4},
  {code: "L67", name: "Gurnam ", exp: 3, location: "Chandigarh", rating: 2},
  {code: "L68", name: "Devarsi ", exp: 5, location: "Jhansi", rating: 4},
  {code: "L69", name: "Anirudh ", exp: 7, location: "Noida", rating: 3},
  {code: "L70", name: "Champak ", exp: 10, location: "Ghaziabad", rating: 3},
  {code: "L71", name: "Batuk ", exp: 14, location: "Joka", rating: 4},
  {code: "L72", name: "Abhijat ", exp: 5, location: "Amritsar", rating: 5},
  {code: "L73", name: "Amil ", exp: 3, location: "Chandigarh", rating: 3},
  {code: "L74", name: "Amogh ", exp: 5, location: "Mohali", rating: 2},
  {code: "L75", name: "Ekanga ", exp: 7, location: "Ludhiana", rating: 4},
  {code: "L76", name: "Ekana ", exp: 10, location: "Hyderabad", rating: 3},
  {code: "L77", name: "Gopesh ", exp: 7, location: "Jhansi", rating: 3},
  {code: "L78", name: "Ashwin ", exp: 9, location: "Hyderabad", rating: 4},
  {code: "L79", name: "Barid ", exp: 10, location: "Jhansi", rating: 5},
  {code: "L80", name: "Daiwik ", exp: 4, location: "Mysore", rating: 5},
  {code: "L81", name: "Etash ", exp: 3, location: "Nagpur", rating: 2},
  {code: "L82", name: "Girish ", exp: 5, location: "Pune", rating: 3},
  {code: "L83", name: "Alagan ", exp: 3, location: "Kolkata", rating: 3},
  {code: "L84", name: "Evyavan ", exp: 5, location: "Noida", rating: 4},
  {code: "L85", name: "Goral ", exp: 7, location: "Ghaziabad", rating: 2},
  {code: "L86", name: "Gadin ", exp: 10, location: "Joka", rating: 4},
  {code: "L87", name: "Alpesh ", exp: 4, location: "Amritsar", rating: 3},
  {code: "L88", name: "Abheek ", exp: 8, location: "Chandigarh", rating: 2},
  {code: "L89", name: "Chinmayu ", exp: 14, location: "Hyderabad", rating: 4},
  {code: "L90", name: "Girivar ", exp: 2, location: "Jhansi", rating: 2},
  {code: "L91", name: "Hardik ", exp: 1, location: "Hyderabad", rating: 3},
  {code: "L92", name: "Aryan ", exp: 3, location: "Jhansi", rating: 2},
  {code: "L93", name: "Amalesh ", exp: 5, location: "Mysore", rating: 5},
  {code: "L94", name: "Avijit ", exp: 7, location: "Nagpur", rating: 2},
  {code: "L95", name: "Dhanesh ", exp: 10, location: "Pune", rating: 5},
  {code: "L96", name: "Durijesh ", exp: 14, location: "Kolkata", rating: 2},
  {code: "L97", name: "Ekaling ", exp: 5, location: "Amritsar", rating: 4},
  {code: "L98", name: "Akshay ", exp: 3, location: "Chandigarh", rating: 2},
  {code: "L99", name: "Avanish ", exp: 5, location: "Jhansi", rating: 4},
  {code: "L100", name: "Ekbal ", exp: 7, location: "Hyderabad", rating: 2},
  {code: "L101", name: "Arjit ", exp: 10, location: "Jhansi", rating: 4},
  {code: "L102", name: "Abhinav ", exp: 7, location: "Mysore", rating: 3},
  {code: "L103", name: "Arnav ", exp: 9, location: "Nagpur", rating: 3},
  {code: "L104", name: "Aadi ", exp: 10, location: "Pune", rating: 4},
  {code: "L105", name: "Bali ", exp: 4, location: "Kolkata", rating: 5},
  {code: "L106", name: "Bharat ", exp: 3, location: "Noida", rating: 3},
  {code: "L107", name: "Ankur ", exp: 5, location: "Ghaziabad", rating: 2},
  {code: "L108", name: "Dhairya ", exp: 3, location: "Joka", rating: 4},
  {code: "L109", name: "Dhirendra ", exp: 5, location: "Amritsar", rating: 3},
  {code: "L110", name: "Dulal ", exp: 7, location: "Chandigarh", rating: 3},
  {code: "L111", name: "Dhaval ", exp: 10, location: "Hyderabad", rating: 4},
  {code: "L112", name: "Ekansh ", exp: 4, location: "Jhansi", rating: 5},
  {code: "L113", name: "Bhav ", exp: 8, location: "Mysore", rating: 5},
  {code: "L114", name: "Anurag ", exp: 14, location: "Jhansi", rating: 2},
  {code: "L115", name: "Arya ", exp: 2, location: "Mysore", rating: 3},
  {code: "L116", name: "Devraj ", exp: 1, location: "Nagpur", rating: 3},
  {code: "L117", name: "Gurudutt ", exp: 3, location: "Pune", rating: 4},
  {code: "L118", name: "Avikam ", exp: 5, location: "Kolkata", rating: 5},
  {code: "L119", name: "Hakesh ", exp: 7, location: "Joka", rating: 2},
  {code: "L120", name: "Arpan ", exp: 10, location: "Amritsar", rating: 3},
  {code: "L121", name: "Damodar ", exp: 14, location: "Chandigarh", rating: 2},
  {code: "L122", name: "Amalendu ", exp: 5, location: "Hyderabad", rating: 5},
  {code: "L123", name: "Dhananjay ", exp: 3, location: "Jhansi", rating: 2},
  {code: "L124", name: "Abhishek ", exp: 5, location: "Mysore", rating: 5},
  {code: "L125", name: "Bhuman ", exp: 7, location: "Nagpur", rating: 2},
  {code: "L126", name: "Chandran ", exp: 10, location: "Pune", rating: 4},
  {code: "L127", name: "Akshaj ", exp: 7, location: "Kolkata", rating: 2},
  {code: "L128", name: "Amal ", exp: 9, location: "Amritsar", rating: 4},
  {code: "L129", name: "Aman ", exp: 10, location: "Chandigarh", rating: 2},
  {code: "L130", name: "Eknath ", exp: 4, location: "Jhansi", rating: 4},
  {code: "L131", name: "Achintya ", exp: 3, location: "Hyderabad", rating: 3},
  {code: "L132", name: "Amir ", exp: 5, location: "Jhansi", rating: 3},
  {code: "L133", name: "Bhaumik ", exp: 3, location: "Mysore", rating: 4},
  {code: "L134", name: "Divyendu ", exp: 5, location: "Nagpur", rating: 5},
  {code: "L135", name: "Amber ", exp: 7, location: "Pune", rating: 3},
  {code: "L136", name: "Asheem ", exp: 10, location: "Kolkata", rating: 2},
  {code: "L137", name: "Ashwini ", exp: 4, location: "Chandigarh", rating: 4},
  {code: "L138", name: "Abhyudaya ", exp: 8, location: "Hyderabad", rating: 2},
  {code: "L139", name: "Dharma ", exp: 14, location: "Jhansi", rating: 4},
  {code: "L140", name: "Ashit ", exp: 2, location: "Mysore", rating: 3},
  {code: "L141", name: "Ashok ", exp: 1, location: "Nagpur", rating: 2},
  {code: "L142", name: "Ednit ", exp: 3, location: "Kolkata", rating: 5},
  {code: "L143", name: "Eha ", exp: 5, location: "Amritsar", rating: 2},
  {code: "L144", name: "Agasthya ", exp: 7, location: "Chandigarh", rating: 3},
  {code: "L145", name: "Amolik ", exp: 10, location: "Kolkata", rating: 2},
  {code: "L146", name: "Dhiren ", exp: 14, location: "Joka", rating: 5},
  {code: "L147", name: "Ekagrah ", exp: 5, location: "Hyderabad", rating: 2},
  {code: "L148", name: "Ekalinga ", exp: 3, location: "Jhansi", rating: 5},
  {code: "L149", name: "Amshul ", exp: 5, location: "Hyderabad", rating: 2},
  {code: "L150", name: "Giriraj ", exp: 7, location: "Jhansi", rating: 4},
  {code: "L151", name: "Gunaja ", exp: 10, location: "Mysore", rating: 2},
  {code: "L152", name: "Gajrup ", exp: 7, location: "Jhansi", rating: 4},
  {code: "L153", name: "Anadi ", exp: 9, location: "Mysore", rating: 2},
  {code: "L154", name: "Ganaraj ", exp: 10, location: "Nagpur", rating: 4},
  {code: "L155", name: "Banaj ", exp: 4, location: "Pune", rating: 3},
  {code: "L156", name: "Amul ", exp: 3, location: "Kolkata", rating: 3},
  {code: "L157", name: "Avanindra ", exp: 5, location: "Amritsar", rating: 4},
  {code: "L158", name: "Govinda ", exp: 3, location: "Chandigarh", rating: 5},
  {code: "L159", name: "Dilip ", exp: 5, location: "Jhansi", rating: 3},
  {code: "L160", name: "Atal ", exp: 7, location: "Hyderabad", rating: 2},
  {code: "L161", name: "Ajit ", exp: 10, location: "Jhansi", rating: 2},
  {code: "L162", name: "Bhupal ", exp: 7, location: "Mysore", rating: 3},
  {code: "L163", name: "Dhilan ", exp: 9, location: "Nagpur", rating: 2},
  {code: "L164", name: "Charan ", exp: 10, location: "Pune", rating: 5},
  {code: "L165", name: "Atmajyoti ", exp: 4, location: "Kolkata", rating: 2},
  {code: "L166", name: "Barindra ", exp: 3, location: "Amritsar", rating: 5},
  {code: "L167", name: "Haresh ", exp: 5, location: "Chandigarh", rating: 2},
  {code: "L168", name: "Aashish ", exp: 3, location: "Jhansi", rating: 4},
  {code: "L169", name: "Bhaskar ", exp: 5, location: "Hyderabad", rating: 2},
  {code: "L170", name: "Bimal ", exp: 7, location: "Chandigarh", rating: 4},
  {code: "L171", name: "Amulya ", exp: 10, location: "Jhansi", rating: 5},
  {code: "L172", name: "Hanuman ", exp: 10, location: "Hyderabad", rating: 2},
  {code: "L173", name: "Ajitesh ", exp: 14, location: "Jhansi", rating: 3},
  {code: "L174", name: "Gagan ", exp: 5, location: "Mysore", rating: 2},
  {code: "L175", name: "Anal ", exp: 3, location: "Nagpur", rating: 5},
  {code: "L176", name: "Anram ", exp: 5, location: "Kolkata", rating: 2},
  {code: "L177", name: "Arha ", exp: 7, location: "Amritsar", rating: 5},
  {code: "L178", name: "Aryaman ", exp: 10, location: "Chandigarh", rating: 2},
  {code: "L179", name: "Dhrupad ", exp: 7, location: "Jhansi", rating: 2},
  {code: "L180", name: "Ekadant ", exp: 9, location: "Hyderabad", rating: 5},
  {code: "L181", name: "Anikait ", exp: 10, location: "Jhansi", rating: 2},
  {code: "L182", name: "Ekavir ", exp: 4, location: "Mysore", rating: 5},
  {code: "L183", name: "Adil ", exp: 3, location: "Nagpur", rating: 2},
  {code: "L184", name: "Barun ", exp: 5, location: "Pune", rating: 4},
  {code: "L185", name: "Darpan ", exp: 3, location: "Kolkata", rating: 2},
  {code: "L186", name: "Apoorva ", exp: 5, location: "Amritsar", rating: 4},
  {code: "L187", name: "Anjor ", exp: 7, location: "Chandigarh", rating: 2},
  {code: "L188", name: "Avtar ", exp: 10, location: "Jhansi", rating: 4},
  {code: "L189", name: "Akand ", exp: 7, location: "Hyderabad", rating: 3},
  {code: "L190", name: "Amod ", exp: 9, location: "Jhansi", rating: 3},
  {code: "L191", name: "Chirag ", exp: 10, location: "Hyderabad", rating: 4},
  {code: "L192", name: "Anirudhha ", exp: 4, location: "Jhansi", rating: 5},
  {code: "L193", name: "Akhil ", exp: 3, location: "Mysore", rating: 3},
  {code: "L194", name: "Bhairav ", exp: 5, location: "Nagpur", rating: 2},
  {code: "L195", name: "Ashvin ", exp: 3, location: "Mysore", rating: 4},
  {code: "L196", name: "Bakool ", exp: 5, location: "Nagpur", rating: 5},
  {code: "L197", name: "Abhijay ", exp: 7, location: "Pune", rating: 4},
  {code: "L198", name: "Amish ", exp: 10, location: "Chandigarh", rating: 2},
  {code: "L199", name: "Dharmesh ", exp: 5, location: "Jhansi", rating: 3},
  {code: "L200", name: "Advay ", exp: 7, location: "Hyderabad", rating: 3},
  {code: "L201", name: "Amol ", exp: 10, location: "Jhansi", rating: 2},
  {code: "L202", name: "Harendra ", exp: 14, location: "Mysore", rating: 5},
  {code: "L203", name: "Ekaraj ", exp: 5, location: "Nagpur", rating: 2},
  {code: "L204", name: "Avilash ", exp: 3, location: "Mysore", rating: 5},
  {code: "L205", name: "Chahel ", exp: 5, location: "Nagpur", rating: 2},
  {code: "L206", name: "Devang ", exp: 7, location: "Pune", rating: 4},
  {code: "L207", name: "Guru ", exp: 10, location: "Kolkata", rating: 2},
  {code: "L208", name: "Biren ", exp: 7, location: "Amritsar", rating: 4},
  {code: "L209", name: "Dinkar ", exp: 9, location: "Chandigarh", rating: 2},
  {code: "L210", name: "Achyuta ", exp: 10, location: "Jhansi", rating: 3},
  {code: "L211", name: "Devesh ", exp: 4, location: "Hyderabad", rating: 2},
  {code: "L212", name: "Gurdeep ", exp: 3, location: "Jhansi", rating: 5},
  {code: "L213", name: "Akash ", exp: 5, location: "Mysore", rating: 2},
  {code: "L214", name: "Gurpreet ", exp: 3, location: "Nagpur", rating: 5},
  {code: "L215", name: "Debjit ", exp: 5, location: "Pune", rating: 2},
  {code: "L216", name: "Animesh ", exp: 7, location: "Kolkata", rating: 4},
  {code: "L217", name: "Anjas ", exp: 10, location: "Mysore", rating: 2},
  {code: "L218", name: "Gaurang ", exp: 7, location: "Nagpur", rating: 4},
  {code: "L219", name: "Akul ", exp: 9, location: "Pune", rating: 2},
  {code: "L220", name: "Amshu ", exp: 10, location: "Chandigarh", rating: 4},
  {code: "L221", name: "Arjun ", exp: 4, location: "Jhansi", rating: 3},
  {code: "L222", name: "Annuabhuj ", exp: 3, location: "Hyderabad", rating: 3},
  {code: "L223", name: "Chandresh ", exp: 5, location: "Jhansi", rating: 4},
  {code: "L224", name: "Amitava ", exp: 3, location: "Mysore", rating: 5},
  {code: "L225", name: "Arav ", exp: 5, location: "Nagpur", rating: 3},
  {code: "L226", name: "Gulal ", exp: 7, location: "Pune", rating: 2},
  {code: "L227", name: "Anish ", exp: 10, location: "Kolkata", rating: 4},
  {code: "L228", name: "Gaurinath ", exp: 1, location: "Amritsar", rating: 2},
  {code: "L229", name: "Aatish ", exp: 3, location: "Chandigarh", rating: 3},
  {code: "L230", name: "Abhijit ", exp: 5, location: "Jhansi", rating: 3},
  {code: "L231", name: "Atmanand ", exp: 7, location: "Hyderabad", rating: 2},
  {code: "L232", name: "Duranjaya ", exp: 10, location: "Jhansi", rating: 5},
  {code: "L233", name: "Basant ", exp: 14, location: "Mysore", rating: 2},
  {code: "L234", name: "Bir ", exp: 5, location: "Nagpur", rating: 5},
  {code: "L235", name: "Diptanshu ", exp: 3, location: "Pune", rating: 2},
  {code: "L236", name: "Ekram ", exp: 5, location: "Kolkata", rating: 4},
  {code: "L237", name: "Devrat ", exp: 7, location: "Chandigarh", rating: 2},
  {code: "L238", name: "Dhimant ", exp: 10, location: "Jhansi", rating: 5},
  {code: "L239", name: "Ekavira ", exp: 7, location: "Hyderabad", rating: 2},
  {code: "L240", name: "Darshan ", exp: 9, location: "Jhansi", rating: 4},
  {code: "L241", name: "Akshat ", exp: 10, location: "Mysore", rating: 2},
  {code: "L242", name: "Anirvinya ", exp: 4, location: "Hyderabad", rating: 4},
  {code: "L243", name: "Bahuliya ", exp: 3, location: "Jhansi", rating: 2},
  {code: "L244", name: "Amitesh ", exp: 5, location: "Mysore", rating: 4},
  {code: "L245", name: "Danvir ", exp: 3, location: "Nagpur", rating: 3},
  {code: "L246", name: "Anupam ", exp: 5, location: "Pune", rating: 3},
  {code: "L247", name: "Ajitabh ", exp: 7, location: "Kolkata", rating: 4},
  {code: "L248", name: "Chinmay ", exp: 10, location: "Amritsar", rating: 5},
  {code: "L249", name: "Deep ", exp: 7, location: "Chandigarh", rating: 3},
  {code: "L250", name: "Gursharan ", exp: 9, location: "Jhansi", rating: 2},
  {code: "L251", name: "Gunamay ", exp: 10, location: "Hyderabad", rating: 2},
  {code: "L252", name: "Adit ", exp: 4, location: "Jhansi", rating: 4},
  {code: "L253", name: "Dyumani ", exp: 3, location: "Mysore", rating: 2},
  {code: "L254", name: "Chatresh ", exp: 5, location: "Nagpur", rating: 3},
  {code: "L255", name: "Gunvant ", exp: 3, location: "Pune", rating: 3},
  {code: "L256", name: "Amartya ", exp: 5, location: "Kolkata", rating: 2},
  {code: "L257", name: "Bibek ", exp: 7, location: "Amritsar", rating: 5},
  {code: "L258", name: "Ansh ", exp: 10, location: "Chandigarh", rating: 2},
  {code: "L259", name: "Daman ", exp: 0, location: "Jhansi", rating: 5},
  {code: "L260", name: "Gaman ", exp: 4, location: "Hyderabad", rating: 2},
  {code: "L261", name: "Dhruv ", exp: 8, location: "Amritsar", rating: 4},
  {code: "L262", name: "Gunaratna ", exp: 14, location: "Chandigarh", rating: 3},
  {code: "L263", name: "Anek ", exp: 2, location: "Jhansi", rating: 3},
  {code: "L264", name: "Azhar ", exp: 1, location: "Hyderabad", rating: 2},
  {code: "L265", name: "Ananta ", exp: 3, location: "Nagpur", rating: 4},
  {code: "L266", name: "Ambuj ", exp: 5, location: "Pune", rating: 2},
  {code: "L267", name: "Ashank ", exp: 7, location: "Kolkata", rating: 3},
  {code: "L268", name: "Bhumi ", exp: 10, location: "Amritsar", rating: 2},
  {code: "L269", name: "Adarsh ", exp: 14, location: "Chandigarh", rating: 5},
  {code: "L270", name: "Atambhu ", exp: 5, location: "Jhansi", rating: 2},
  {code: "L271", name: "Ankush ", exp: 3, location: "Hyderabad", rating: 5},
  {code: "L272", name: "Chiranjiv ", exp: 5, location: "Jhansi", rating: 2},
  {code: "L273", name: "Chatura ", exp: 7, location: "Mysore", rating: 4},
  {code: "L274", name: "Ghanshyam ", exp: 10, location: "Nagpur", rating: 2},
  {code: "L275", name: "Brijesh ", exp: 7, location: "Pune", rating: 4},
  {code: "L276", name: "Chain ", exp: 9, location: "Kolkata", rating: 2},
  {code: "L277", name: "Anshuman ", exp: 10, location: "Mysore", rating: 4},
  {code: "L278", name: "Chintan ", exp: 4, location: "Nagpur", rating: 3},
  {code: "L279", name: "Devkumar ", exp: 3, location: "Pune", rating: 3},
  {code: "L280", name: "Gopan ", exp: 5, location: "Kolkata", rating: 4},
  {code: "L281", name: "Dipendu ", exp: 3, location: "Jhansi", rating: 5},
  {code: "L282", name: "Atraiu ", exp: 5, location: "Hyderabad", rating: 3},
  {code: "L283", name: "Ganapati ", exp: 7, location: "Pune", rating: 2},
  {code: "L284", name: "Ehimay ", exp: 10, location: "Kolkata", rating: 4},
  {code: "L285", name: "Abhiraj ", exp: 0, location: "Amritsar", rating: 2},
  {code: "L286", name: "Barsaat ", exp: 4, location: "Chandigarh", rating: 4},
  {code: "L287", name: "Amrish ", exp: 8, location: "Chandigarh", rating: 2},
  {code: "L288", name: "Bhavesh ", exp: 14, location: "Jhansi", rating: 4},
  {code: "L289", name: "Badal ", exp: 2, location: "Hyderabad", rating: 3},
  {code: "L290", name: "Durjaya ", exp: 1, location: "Pune", rating: 3},
  {code: "L291", name: "Advaita ", exp: 3, location: "Kolkata", rating: 4},
  {code: "L292", name: "Aaditya ", exp: 5, location: "Amritsar", rating: 5},
  {code: "L293", name: "Devaj ", exp: 7, location: "Chandigarh", rating: 3},
  {code: "L294", name: "Aseem ", exp: 10, location: "Jhansi", rating: 2},
  {code: "L295", name: "Bhupad ", exp: 14, location: "Hyderabad", rating: 3},
  {code: "L296", name: "Chetan ", exp: 5, location: "Jhansi", rating: 2},
  {code: "L297", name: "Grishm ", exp: 3, location: "Mysore", rating: 5},
  {code: "L298", name: "Avi ", exp: 5, location: "Nagpur", rating: 2},
  {code: "L299", name: "Giridhar ", exp: 7, location: "Pune", rating: 5},
  {code: "L300", name: "Bhargav ", exp: 10, location: "Kolkata", rating: 2}
])
Servicelist.create!([
  {code: "L111", servicecode: "S3", servicename: " Divorce", charges: 15000},
  {code: "L86", servicecode: "S13", servicename: "Book-keeping", charges: 1800},
  {code: "L159", servicecode: " S2", servicename: " Trademark Filing", charges: 5000},
  {code: "L102", servicecode: "S11", servicename: "Accounting", charges: 12000},
  {code: "L86", servicecode: "S6", servicename: "Company Registration", charges: 30000},
  {code: "L239", servicecode: "S8", servicename: "PAN Card", charges: 999},
  {code: "L211", servicecode: "S20", servicename: "Annual Return Filing", charges: 25000},
  {code: "L202", servicecode: "S18", servicename: "Copyright Registration", charges: 1500},
  {code: "L255", servicecode: "S3", servicename: " Divorce", charges: 15000},
  {code: "L120", servicecode: " S1", servicename: " LLP Registration", charges: 10000},
  {code: "L222", servicecode: "S11", servicename: "Accounting", charges: 14000},
  {code: "L220", servicecode: "S15", servicename: "Death Certificate", charges: 1000},
  {code: "L9", servicecode: "S3", servicename: " Divorce", charges: 10000},
  {code: "L83", servicecode: "S20", servicename: "Annual Return Filing", charges: 15000},
  {code: "L183", servicecode: " S2", servicename: " Trademark Filing", charges: 8000},
  {code: "L277", servicecode: "S10", servicename: "Form a Trust", charges: 20000},
  {code: "L165", servicecode: "S19", servicename: "Patent filing", charges: 10000},
  {code: "L118", servicecode: " S1", servicename: " LLP Registration", charges: 20000},
  {code: "L299", servicecode: " S2", servicename: " Trademark Filing", charges: 7000},
  {code: "L171", servicecode: "S6", servicename: "Company Registration", charges: 12000},
  {code: "L46", servicecode: "S7", servicename: "NGO Registration", charges: 50000},
  {code: "L4", servicecode: "S8", servicename: "PAN Card", charges: 299},
  {code: "L269", servicecode: "S3", servicename: " Divorce", charges: 15000},
  {code: "L168", servicecode: " S2", servicename: " Trademark Filing", charges: 12000},
  {code: "L160", servicecode: "S11", servicename: "Accounting", charges: 18000},
  {code: "L235", servicecode: "S7", servicename: "NGO Registration", charges: 35000},
  {code: "L20", servicecode: "S11", servicename: "Accounting", charges: 10000},
  {code: "L278", servicecode: " S2", servicename: " Trademark Filing", charges: 10000},
  {code: "L78", servicecode: "S8", servicename: "PAN Card", charges: 200},
  {code: "L25", servicecode: "S10", servicename: "Form a Trust", charges: 11000},
  {code: "L9", servicecode: "S8", servicename: "PAN Card", charges: 199},
  {code: "L117", servicecode: "S5", servicename: "Trademark Objection", charges: 4000},
  {code: "L213", servicecode: "S3", servicename: " Divorce", charges: 12000},
  {code: "L118", servicecode: "S13", servicename: "Book-keeping", charges: 2000},
  {code: "L290", servicecode: "S3", servicename: " Divorce", charges: 20000},
  {code: "L130", servicecode: "S8", servicename: "PAN Card", charges: 299},
  {code: "L86", servicecode: "S20", servicename: "Annual Return Filing", charges: 12000},
  {code: "L62", servicecode: "S10", servicename: "Form a Trust", charges: 20000},
  {code: "L163", servicecode: "S8", servicename: "PAN Card", charges: 250},
  {code: "L101", servicecode: "S7", servicename: "NGO Registration", charges: 15000},
  {code: "L243", servicecode: " S2", servicename: " Trademark Filing", charges: 10000},
  {code: "L170", servicecode: "S11", servicename: "Accounting", charges: 10000},
  {code: "L170", servicecode: "S13", servicename: "Book-keeping", charges: 1000},
  {code: "L202", servicecode: " S2", servicename: " Trademark Filing", charges: 5000},
  {code: "L278", servicecode: "S19", servicename: "Patent filing", charges: 25000},
  {code: "L272", servicecode: "S4", servicename: " LLP Registration", charges: 15000},
  {code: "L10", servicecode: "S11", servicename: "Accounting", charges: 12000},
  {code: "L212", servicecode: "S15", servicename: "Death Certificate", charges: 1899},
  {code: "L249", servicecode: "S10", servicename: "Form a Trust", charges: 10000},
  {code: "L247", servicecode: "S8", servicename: "PAN Card", charges: 200},
  {code: "L165", servicecode: " S2", servicename: " Trademark Filing", charges: 8000},
  {code: "L253", servicecode: "S13", servicename: "Book-keeping", charges: 999},
  {code: "L240", servicecode: "S7", servicename: "NGO Registration", charges: 18000},
  {code: "L243", servicecode: "S19", servicename: "Patent filing", charges: 25000},
  {code: "L286", servicecode: "S10", servicename: "Form a Trust", charges: 20000},
  {code: "L200", servicecode: "S10", servicename: "Form a Trust", charges: 40000},
  {code: "L173", servicecode: "S11", servicename: "Accounting", charges: 15000},
  {code: "L299", servicecode: "S19", servicename: "Patent filing", charges: 20000},
  {code: "L232", servicecode: " S2", servicename: " Trademark Filing", charges: 5000},
  {code: "L264", servicecode: "S19", servicename: "Patent filing", charges: 15000},
  {code: "L44", servicecode: "S20", servicename: "Annual Return Filing", charges: 10000},
  {code: "L222", servicecode: "S13", servicename: "Book-keeping", charges: 1500},
  {code: "L227", servicecode: "S13", servicename: "Book-keeping", charges: 1000},
  {code: "L240", servicecode: "S10", servicename: "Form a Trust", charges: 16000},
  {code: "L9", servicecode: "S16", servicename: "Passport", charges: 4999},
  {code: "L78", servicecode: "S3", servicename: " Divorce", charges: 10000},
  {code: "L5", servicecode: "S19", servicename: "Patent filing", charges: 10000},
  {code: "L235", servicecode: "S10", servicename: "Form a Trust", charges: 50000},
  {code: "L67", servicecode: "S3", servicename: " Divorce", charges: 10000},
  {code: "L9", servicecode: "S15", servicename: "Death Certificate", charges: 6000},
  {code: "L42", servicecode: "S19", servicename: "Patent filing", charges: 10000},
  {code: "L42", servicecode: " S2", servicename: " Trademark Filing", charges: 15000},
  {code: "L253", servicecode: "S12", servicename: "Auditing", charges: 10000},
  {code: "L244", servicecode: "S7", servicename: "NGO Registration", charges: 5000},
  {code: "L188", servicecode: "S3", servicename: " Divorce", charges: 15000},
  {code: "L20", servicecode: "S12", servicename: "Auditing", charges: 5000},
  {code: "L10", servicecode: " S1", servicename: " LLP Registration", charges: 10001},
  {code: "L42", servicecode: "S6", servicename: "Company Registration", charges: 9999},
  {code: "L101", servicecode: "S6", servicename: "Company Registration", charges: 10000},
  {code: "L46", servicecode: "S10", servicename: "Form a Trust", charges: 22000},
  {code: "L253", servicecode: "S20", servicename: "Annual Return Filing", charges: 100000},
  {code: "L103", servicecode: "S13", servicename: "Book-keeping", charges: 1500},
  {code: "L86", servicecode: "S12", servicename: "Auditing", charges: 5600},
  {code: "L165", servicecode: "S18", servicename: "Copyright Registration", charges: 3000},
  {code: "L200", servicecode: "S7", servicename: "NGO Registration", charges: 45000},
  {code: "L183", servicecode: "S18", servicename: "Copyright Registration", charges: 2000},
  {code: "L112", servicecode: "S8", servicename: "PAN Card", charges: 250},
  {code: "L171", servicecode: " S1", servicename: " LLP Registration", charges: 15000},
  {code: "L102", servicecode: "S9", servicename: "Form a Society", charges: 10000},
  {code: "L62", servicecode: "S9", servicename: "Form a Society", charges: 15000},
  {code: "L54", servicecode: "S17", servicename: "Property Registration", charges: 9999},
  {code: "L224", servicecode: " S2", servicename: " Trademark Filing", charges: 10000},
  {code: "L227", servicecode: "S12", servicename: "Auditing", charges: 5000},
  {code: "L290", servicecode: "S10", servicename: "Form a Trust", charges: 20000},
  {code: "L118", servicecode: "S10", servicename: "Form a Trust", charges: 15000},
  {code: "L280", servicecode: " S2", servicename: " Trademark Filing", charges: 8000},
  {code: "L20", servicecode: "S13", servicename: "Book-keeping", charges: 10000},
  {code: "L264", servicecode: " S2", servicename: " Trademark Filing", charges: 5000},
  {code: "L175", servicecode: "S6", servicename: "Company Registration", charges: 25000},
  {code: "L183", servicecode: "S5", servicename: "Trademark Objection", charges: 5000},
  {code: "L70", servicecode: "S11", servicename: "Accounting", charges: 25000},
  {code: "L292", servicecode: "S10", servicename: "Form a Trust", charges: 15000},
  {code: "L173", servicecode: " S1", servicename: " LLP Registration", charges: 8000},
  {code: "L164", servicecode: "S10", servicename: "Form a Trust", charges: 25000},
  {code: "L147", servicecode: "S8", servicename: "PAN Card", charges: 300},
  {code: "L25", servicecode: " S1", servicename: " LLP Registration", charges: 10000},
  {code: "L38", servicecode: "S11", servicename: "Accounting", charges: 20000},
  {code: "L258", servicecode: "S20", servicename: "Annual Return Filing", charges: 20000},
  {code: "L167", servicecode: "S19", servicename: "Patent filing", charges: 10000},
  {code: "L65", servicecode: " S2", servicename: " Trademark Filing", charges: 5000},
  {code: "L197", servicecode: " S2", servicename: " Trademark Filing", charges: 10000},
  {code: "L173", servicecode: "S6", servicename: "Company Registration", charges: 10000},
  {code: "L183", servicecode: "S19", servicename: "Patent filing", charges: 20000},
  {code: "L208", servicecode: "S7", servicename: "NGO Registration", charges: 12000},
  {code: "L44", servicecode: "S11", servicename: "Accounting", charges: 10000},
  {code: "L208", servicecode: "S9", servicename: "Form a Society", charges: 12000},
  {code: "L67", servicecode: "S8", servicename: "PAN Card", charges: 500},
  {code: "L70", servicecode: "S6", servicename: "Company Registration", charges: 8000},
  {code: "L86", servicecode: "S11", servicename: "Accounting", charges: 10000},
  {code: "L167", servicecode: " S2", servicename: " Trademark Filing", charges: 5000},
  {code: "L278", servicecode: "S18", servicename: "Copyright Registration", charges: 5000},
  {code: "L173", servicecode: "S13", servicename: "Book-keeping", charges: 999},
  {code: "L12", servicecode: "S9", servicename: "Form a Society", charges: 24999},
  {code: "L164", servicecode: " S1", servicename: " LLP Registration", charges: 6000},
  {code: "L83", servicecode: "S11", servicename: "Accounting", charges: 12000},
  {code: "L192", servicecode: "S3", servicename: " Divorce", charges: 20000},
  {code: "L171", servicecode: "S7", servicename: "NGO Registration", charges: 25000},
  {code: "L25", servicecode: " S2", servicename: " Trademark Filing", charges: 20000},
  {code: "L190", servicecode: "S14", servicename: "Birth Certificate", charges: 1099},
  {code: "L170", servicecode: "S20", servicename: "Annual Return Filing", charges: 20000},
  {code: "L103", servicecode: "S11", servicename: "Accounting", charges: 10000},
  {code: "L164", servicecode: "S7", servicename: "NGO Registration", charges: 29000},
  {code: "L5", servicecode: " S2", servicename: " Trademark Filing", charges: 6000},
  {code: "L243", servicecode: "S18", servicename: "Copyright Registration", charges: 1000},
  {code: "L208", servicecode: "S10", servicename: "Form a Trust", charges: 20000},
  {code: "L170", servicecode: "S12", servicename: "Auditing", charges: 15000},
  {code: "L183", servicecode: "S5", servicename: "Trademark Objection", charges: 4000},
  {code: "L227", servicecode: "S11", servicename: "Accounting", charges: 12000},
  {code: "L86", servicecode: "S8", servicename: "PAN Card", charges: 400},
  {code: "L1", servicecode: " S1", servicename: " LLP Registration", charges: 6999},
  {code: "L120", servicecode: "S6", servicename: "Company Registration", charges: 14000},
  {code: "L185", servicecode: "S8", servicename: "PAN Card", charges: 200},
  {code: "L290", servicecode: "S19", servicename: "Patent filing", charges: 50000},
  {code: "L253", servicecode: "S11", servicename: "Accounting", charges: 15000},
  {code: "L102", servicecode: "S13", servicename: "Book-keeping", charges: 1200},
  {code: "L118", servicecode: "S11", servicename: "Accounting", charges: 12000},
  {code: "L202", servicecode: "S5", servicename: "Trademark Objection", charges: 6000},
  {code: "L147", servicecode: "S15", servicename: "Death Certificate", charges: 499},
  {code: "L12", servicecode: "S7", servicename: "NGO Registration", charges: 19999},
  {code: "L175", servicecode: " S1", servicename: " LLP Registration", charges: 10000},
  {code: "L82", servicecode: "S8", servicename: "PAN Card", charges: 300},
  {code: "L190", servicecode: "S15", servicename: "Death Certificate", charges: 1500},
  {code: "L62", servicecode: "S7", servicename: "NGO Registration", charges: 10000},
  {code: "L3", servicecode: "S4", servicename: " LLP Registration", charges: 15000},
  {code: "L91", servicecode: "S15", servicename: "Death Certificate", charges: 10000},
  {code: "L280", servicecode: "S19", servicename: "Patent filing", charges: 8999}
])
